version: "3"

services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
      - "5678:5678"   # <-- For debugging
    depends_on:
      - db
    #  - elasticsearch  
    environment:
      DATABASE_URL: postgres://geek_space_admin:159753qwerty@db:5432/geek_space_db
      FLASK_ENV: development   # <-- For debugging
    
      
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: geek_space_admin
      POSTGRES_PASSWORD: 159753qwerty
      POSTGRES_DB: geek_space_db

  