"""added column 'edited'

Revision ID: 83b6bcd5dd74
Revises: 009073b6ce46
Create Date: 2023-03-19 02:01:46.000110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b6bcd5dd74'
down_revision = '009073b6ce46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('edited')

    # ### end Alembic commands ###
